# Generated by Django 5.2.3 on 2025-07-07 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('symptoms', models.TextField()),
                ('doctor_type', models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Psychiatrist', 'Psychiatrist'), ('Pulmonologist', 'Pulmonologist')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
